### ISSUE TITLE
Implement Nested Reverse Conversion Method from CSV to JSON

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/json-csv#5]
Currently, when one uses the output of JSON to CSV conversion as an input of CSV to JSON, one does not get the same input provided in the first place.

**Example Scenario:**

```php
$csv = (new Json('whatever.json'))->convertAndSave('whatever.csv');
$json = (new Csv('whatever.csv'))->convertAndSave('whatever-new.json');
file_get_contents('whatever.json') === file_get_contents('whatever-new.json');
```
Here are the input and the output files for the example scenario.

**Input: whatever.json**
```json
[
  {
    "name": {
      "common": "Turkey"
    },
    "latlng": [39, 35]
  }
]
```

**Output: whatever.csv**

**name\_common**|**latlng\_0**|**latlng\_1**
:-----:|:-----:|:-----:
Turkey|39|35

**Output: whatever-2.json**
```json
[{"name_common":"Turkey","latlng_0":"39","latlng_1":"35"}]
```

What is expected is a new method when used converts `whatever.csv` to `whatever.json` again instead of `whatever-2.json`.

**Comment by intelliapps** [comment]
Clearly there is an issue with the actual JSON but do you care whether the output is formatted, give that an IDE or other tool can format JSON to make it more readable when that is required?

**Comment by ozdemirburak** [comment]
No, formatting is not a problem actually, just setting the encoding option in the end like below will also take care of it.

```php
$csv->setConversionKey('options', JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
```

**Comment by intelliapps** [comment]
Is it safe to assume that the JSON key names in the original input will never contain the underscore character? Otherwise I don't think the can be fully resolved by replacing convertAndSave()?

**Comment by intelliapps** [comment]
As per the comments on my pull request: I've implemented changes to get the output of csv->json to match the input to json->csv. The result is a significant improvement but there are still issues which I don't think can be resolved without changing the conversion from json to csv, or at least without further consideration.

1) Previously, the json output represented all values as strings, wrapped in double quotes. As the example input above contains numeric values, along with most of the other test data, this resulted in a mismatch between the input and output json. I have resolved this by adding a 'numbers' conversion option which defaults to 'strings' but when set to 'numbers' causes all numeric strings to be converted to numeric types. This can still result in mis-matching input / output json where:
    a) input contains numeric f.p. values with 0 fractional value, e.g. 6.0 is output as 6
    b) input contains a mix of numbers and numeric strings

2) With the stats data, the name of each object from the stats.json file is lost when it is converted to csv, e.g. "kemal-kilicdaroglu" and "muharrem-ince". This is consistent with the stored stats.csv test file, which does not contain these values. Since these values are not in the csv at all I can't even consider how to reinstate them into the output json to make it match the input. A related issue is that the outer braces are then {} where they should be [].

3) With the stats data the "avg" values from the input json are rounded to fewer digits during the json to csv conversion, which means that it is not possible for the values in the output json to match.
